### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by ghostskull789**
we got a long way since the home page here, lets merge the changes and make a check point

### CODE REVIEW

**Comment by vaibssingh** [comment]
Damn!

**Comment by vaibssingh** [comment]
Don't we have any ci/cd setup to check the builds automatically? @leron8

**Comment by vaibssingh** [comment]
Okay, I just realised we gotta pay for it separately. Never mind.

**Comment by leron8** [comment]
Thanks @ghostskull789 . And naa not yet @vaibssingh plus we also took too long to merge and release. We should get better at this from now on.

**Pull request merged**
