### PR TITLE
Profile Page Proofreading

### PR DESCRIPTION
**Pull request by Of-Elysium**
Major proofreading across all files. No actual content changed besides displayed English text.
Will definitely be going in for round 2 at a later time.
I did not change the color/gradient of the NavBar; I will leave that up to our design team.
**Content writing at its finest!**

### CODE REVIEW

**Comment by vaibssingh** [comment]
Thanks a lot for your contribution @Of-Elysium :+1: :)

**Comment by leron8** [comment]
Hello @Of-Elysium ! thank you very much for your contributions. Those are some nice edits on the content 👍 From checking it out I only see a possible issue where you did some changes on the styles for the Profile Component, and those would also need to be changed on the Profile's JSX. So it'll cause some issues on the Profile's styling right @ghostskull789 ?

**Comment by Of-Elysium** [comment]
You're absolutely right. I actually did make the edits on the JSX but
completely forgot to commit the changes. Allow me to remedy that!

**Comment by Of-Elysium** [comment]
I re-checked all the JSX codes against the CSS. I believe everything _appears_ to be in order. But if I did end up destroying everything just let me know and I'll debug again

**Comment by leron8** [comment]
Allright @Of-Elysium. I'll test the changes and merge into the branch later after work. Thanks again for your contributions.

**Pull request merged**
